repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff lint
        entry: ruff check --fix --config=src/pyproject.toml
        language: system
        types: [python]
        files: ^src/

      - id: ruff-format
        name: ruff format
        entry: ruff format --config=src/pyproject.toml
        language: system
        types: [python]
        files: ^src/

      - id: mypy
        name: mypy strict
        entry: mypy --config-file=src/pyproject.toml
        language: system
        types: [python]
        files: ^src/
        exclude: ^src/(\.venv|__pycache__)/
